### ISSUE TITLE
UnitAura changed in WoW 8.0

### ISSUE THREAD

**Issue by VaporAPX** [phanx-wow/LibResInfo#15] opened 2018-04-29 19:32 UTC
I use ouf_Drk for unit frames and when I enable them in the BFA beta I get the following error:

> 3x ...ddOns\oUF_Drk\libs\LibResInfo-1.0\LibResInfo-1.0-24.lua:574: Usage: UnitAura("unit", [index][, "filter"])
[C]: ?
...ddOns\oUF_Drk\libs\LibResInfo-1.0\LibResInfo-1.0-24.lua:574: in function UNIT_AURA' ...ddOns\oUF_Drk\libs\LibResInfo-1.0\LibResInfo-1.0-24.lua:313: in function <...ddOns\oUF_Drk\libs\LibResInfo-1.0\LibResInfo-1.0.lua:306> ...ddOns\oUF_Drk\libs\LibResInfo-1.0\LibResInfo-1.0-24.lua:328: in functionGROUP_ROSTER_UPDATE'
...ddOns\oUF_Drk\libs\LibResInfo-1.0\LibResInfo-1.0-24.lua:156: in function OnUsed' ...er4\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:168: in functionRegisterCallback'
oUF_Drk\elements\ResInfo.lua:99: in main chunk
Locals:
(*temporary) = "player"
(*temporary) = "Soulstone"

I'm assuming this to be a Library issue and with the new changes in 8.0 and UnitAura.  Thanks!

**Comment by Phanx** [comment] 2018-05-04 16:58
It looks like oUF_Drk is bundling an out of date version of LRI; there were significant changes between 24 (the version you've got) and 25 (the latest version). Please:

1. download the latest version of the library (links on the main GitHub page),
2. install it as a standalone addon (it will override the older version in oUF_Drk),
3. restart WoW, and
4. run `/run LoadAddOn("LibResInfo-1.0")` in-game to make sure the standalone version got loaded (oUF_Drk may not be set up correctly to load external versions).

Then report back as to whether or not the same error occurs.

**Comment by Phanx** [comment] 2018-05-04 19:40
Probably fixed in 1076dcfb98c4ade4a9c79f49d84eda42d8402be7 but I don't have beta access, so I can't test it myself. Here's how you can:

1. Install the [latest release version](https://github.com/phanx-wow/LibResInfo/releases/download/25b/LibResInfo-1.0-25b.zip) as a standalone addon
2. Save the latest [development version of LibResInfo-1.0.lua](https://github.com/phanx-wow/LibResInfo/raw/master/LibResInfo-1.0.lua) over the top of the installed one
3. Restart WoW
4. Type `/run LoadAddOn("LibResInfo-1.0")` (this should happen automatically but oUF_Drk may not be configured properly to support libraries installed as standalone addons)

If you don't see any error messages, but res detection doesn't seem to be working:

1. Enable debugging by typing `/lri 3`
2. If you use ChatFrame3 for something else, move debugging to an unused frame, e.g. `/lri ChatFrame5`
3. Make sure the specified chat frame exists, otherwise you won't be able to see the messages
4. Reproduce the problem, then [copy](https://www.curseforge.com/wow/addons/chat_copy) or screenshot the debugging messages and post them here

**Comment by VaporAPX** [comment] 2018-05-04 19:51
Perfect, thank you for this, I will install as you mentioned and report back to you once I get some testing.  I have been working with the author of ouf_drk as well and this particular error no longer happens currently,  nonetheless I'll install and see if any errors come during gameplay.  

Thank you again.

**Comment by bruneski** [comment] 2018-07-23 21:10
Any update on when this fix will be pushed to production and available via Twitch App?

**Comment by Phanx** [comment] 2018-07-29 10:51
Done. The OP never followed up, and I don't have the ability to test it myself without an active account, but no errors come up when logging into a low level character and running around, so I guess it works.

**Closed by Phanx** 2018-07-29 10:51 UTC
Labels: bug
